### ISSUE TITLE
About form's netid

### ISSUE THREAD

**Issue by rhnkyr** [joeauty/RememberMe-CodeIgniter-Spark#1]
Hi Joe,

i did not get really what "(where $this->input->post('netid') is your form's netid)" means. Can you provide an example pls... Thansk in advance...

**Comment by joeauty** [comment]
Hello,

The spark captures input from your login form so that it is invoked when a "remember me" checkbox is checked. The netid  will be in this form too, it is obviously needed for logging in, this is what this refers to.

If the term "netid" threw you, I meant username, userid, or whatever else.. all interchangeable.

**Comment by rhnkyr** [comment]
Got it mate. Thank you.

**Comment by joeauty** [comment]
No problem, please let me know when you get this working and how this works out for you!

**Comment by rhnkyr** [comment]
I have just implemented it as you describe. But as far as i undertand, it supports just one browser's cookie. I tried second browser(no mather which broser is) and ci_cookie row on db has altered. Can you alter ur code that handles multiple browsers' cookies? (Or maybe it can handle. I am new on CI btw.)

**Comment by joeauty** [comment]
I've thought about supporting multiple browser cookies in a future release, but just haven't gotten around to this yet. If you are interested in working on this feature, please feel free to fork the project and send a pull request with your changes, and I will gladly implement them and give you credit for your work!

**Comment by rhnkyr** [comment]
i c. So let me check it out then :)...
