### ISSUE TITLE
Core controller and Authentication Check

### ISSUE THREAD

**Issue by junosapien** [joeauty/RememberMe-CodeIgniter-Spark#3]
Hi Joe,

I've been reading over the documentation for this as I am looking to add a 'remember me' check box to an existing authentication system on a CI site. I will admit to not being much more than a newbie with CI, so I ask for your patience. What exactly do you mean by this statement "I like to put this code in my CodeIgniter core controller..."? How would one do that?

The statement continues " ...so that this authentication check occurs on every page load". I wouldn't want this to run on every page load - just the initial page load when the user navigates back to the site - their entry point, as it were. Any suggestions as to how to do that?

Thanks!

**Comment by joeauty** [comment]
Hi Juno,

Have you looked at this page? http://ellislab.com/codeigniter/user-guide/general/core_classes.html  it describes creating core controllers (and other core elements). A core controller is a controller that runs each time any CodeIgniter controller is run, i.e. a bunch of code that runs before any controller code has run.

If you don't want to verify cookies on each page load, simply add this code to your individual controller rather than creating a core controller (which won't exist in the default CodeIgniter file structure).

Does this make sense?

**Comment by chaitu111** [comment]
function setCookie($netid = "", $nocookie = false) 
 
what is $netid?
why are you setting $nocookie = false intiallay
what is the meaning of $nocookie  variable ?
